before:
  hooks:
    - go mod tidy
    - go test ./pkg/vcb

builds:
  -
    id: "vcbtool"
    dir: .
    main: ./cmd/vcbtool
    binary: vcbtool
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
